name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read
  id-token: write

defaults:
  run:
    shell: bash # Every steps will have a /usr/bin/bash --noprofile --norc -e -o pipefail

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://docs.gatling.io
    timeout-minutes: 10
    steps:
      - name: Checkout current project
        uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'
          # no cache

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Build JVM code samples
        run: sbt "all headerCheckAll scalafmtSbtCheck" "test"

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          # no cache

      - name: Setup Hugo
        uses: ./.github/actions/setup-hugo
        with:
          hugo-version: '0.142.0'

      - name: Prepare project
        run: ./bin/entrypoint.sh prepare

      - name: Build TypeScript code samples
        run: npm run test-ts-samples

      - name: Generate documentation
        run: ./bin/entrypoint.sh --noprepare generate

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-region: eu-west-3
          role-to-assume: ${{ secrets.AWS_ROLE_PROD_DOC }}

      - name: Deploy
        run: |
          sed -i 's/HUGO_DEPLOYMENT_BUCKET/${{ secrets.HUGO_DEPLOYMENT_BUCKET }}/' config/production/config.yaml
          sed -i 's/HUGO_DEPLOYMENT_CLOUDFRONT_DISTRIBUTION_ID/${{ secrets.HUGO_DEPLOYMENT_CLOUDFRONT_DISTRIBUTION_ID }}/' config/production/config.yaml
          hugo deploy --maxDeletes -1 --invalidateCDN
